name: Push latest tag to DockerHub 

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - setup-files/**
  pull_request:
    branches: [ main ]
    paths:
      - Dockerfile
      - setup-files/**

  workflow_dispatch:

# https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKER }}
      -    
        name: Checkout
        uses: actions/checkout@v4.2.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      -
        name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
        # platforms: linux/amd64,linux/arm64
          push: true
          tags: ezaul/ledfx-docker:latest
